"""
main.py  —  FastAPI application entry point
============================================
Mounts all route modules and configures CORS, GZip compression,
and a 5-minute server-side timeout for long-running ML operations.
"""
import logging
import sys
import os
from contextlib import asynccontextmanager

# Allow imports from project root (ml_pipeline, database)
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# ── Logging ────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%H:%M:%S",
    handlers=[logging.StreamHandler(sys.stdout)],
)
logger = logging.getLogger(__name__)

from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.gzip import GZipMiddleware
from fastapi.responses import JSONResponse

from backend.services.gemini_service import generate_fairness_audit, reset_gemini_session

from backend.routes import (
    bias,
    cleaning,
    eda,
    evaluation,
    features,
    imbalance,
    predictions,
    preprocessing,
    reports,
    split,
    training,
    upload,
)
from database.db_config import init_db


# ── Lifespan ───────────────────────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    """Initialise DB on startup; cleanup on shutdown."""
    init_db()
    yield


app = FastAPI(
    title="Unbiased AI Decision Dashboard API",
    description="End-to-end ML pipeline with bias detection and fairness metrics.",
    version="1.1.0",
    docs_url="/docs",
    redoc_url="/redoc",
    lifespan=lifespan,
)

# ── GZip Compression ──────────────────────────────────────────────────
# Automatically compresses responses larger than 1 KB.
# Reduces payload by 60–80 % for large JSON bodies (EDA, evaluation).
app.add_middleware(GZipMiddleware, minimum_size=1024)

# ── CORS ───────────────────────────────────────────────────────────────
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:5173", "http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Routers ────────────────────────────────────────────────────────────
app.include_router(upload.router)
app.include_router(cleaning.router)
app.include_router(split.router)
app.include_router(preprocessing.router)
app.include_router(eda.router)
app.include_router(features.router)
app.include_router(imbalance.router)
app.include_router(training.router)
app.include_router(evaluation.router)
app.include_router(bias.router)
app.include_router(predictions.router)
app.include_router(reports.router)


@app.get("/", tags=["Health"])
async def root():
    return {"status": "ok", "message": "Unbiased AI Decision Dashboard API is running."}


@app.get("/health", tags=["Health"])
async def health():
    return {"status": "healthy"}


# ── Gemini Fairness Audit ──────────────────────────────────────────────
@app.post("/api/fairness-audit", tags=["Fairness"])
async def fairness_audit(request: Request):
    """
    POST /api/fairness-audit
    -------------------------
    Accept structured ML evaluation data (JSON body) and return an
    AI-powered fairness & bias audit generated by Gemini 1.5 Flash.

    Example request body:
    {
      "model_name": "RandomForest",
      "metrics": {"accuracy": 0.87, "precision": 0.61, "recall": 0.34, "f1": 0.44},
      "class_distribution": {"0": {"count": 820, "pct": 82.0}, "1": {"count": 180, "pct": 18.0}},
      "threshold": 0.5,
      "feature_importance": [{"feature": "age", "importance": 0.42}],
      "group_metrics": {"male": {"accuracy": 0.91}, "female": {"accuracy": 0.73}}
    }
    """
    try:
        data = await request.json()
    except Exception:
        return JSONResponse(
            status_code=400,
            content={"status": "error", "message": "Invalid JSON body."},
        )

    if not isinstance(data, dict) or not data:
        return JSONResponse(
            status_code=400,
            content={
                "status": "error",
                "message": "Request body must be a non-empty JSON object.",
            },
        )

    result = generate_fairness_audit(data)

    if result["status"] == "error":
        return JSONResponse(status_code=502, content=result)

    return JSONResponse(status_code=200, content=result)
